### ISSUE TITLE
Celery 4.x triggering some "CRITICAL" warnings running locally on windows

### ISSUE THREAD

**Issue by popenc** [quanted/qed_cts#2]
This is the following error I'm getting when running celery workers locally on my windows 10 machine:

`[2017-03-14 10:04:15,819: CRITICAL/MainProcess] Unrecoverable error: TypeError('argument 1 must be an integer, not _subprocess_handle',)
Traceback (most recent call last):
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\celery\bootsteps.py", line 370, in start
    return self.obj.start()
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\popen_spawn_win32.py", line 64, in __init__
    _winapi.CloseHandle(ht)
TypeError: argument 1 must be an integer, not _subprocess_handle

(env) c:\Users\nickpope\Documents\GitHub\qed_cts\cts_celery>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\spawn.py", line 159, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\Users\nickpope\Documents\GitHub\qed_cts\env\lib\site-packages\billiard\reduction.py", line 121, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
WindowsError: [Error 87] The parameter is incorrect`

**Comment by popenc** [comment]
This has been a closed issue on celery's github page: https://github.com/celery/celery/issues/3551

Current celery version in qed_cts virtual environment: 4.0.2 -- triggered above errors

Working celery version on local machine: 3.1.23 (Cipater)

**Comment by popenc** [comment]
This seems to only be a problem with Celery 4 and windows, so it won't affect anything in prod. I'm currently working around this by running celery workers outside the qed_cts virtual environment, so it'll use 3.1.23 instead, but it's not a very stable solution and perhaps there's a way to use a differing version dynamically based on platform.
